
springboot:
  jwt:
    access-secret: DeaguGreenArtAcademyClass502ForJavaSpringBootaaaasdf
    refresh-secret: HelloWorldRefreshTokenCreateBySecretHaHaaasdfasdf

    token-type: Bearer
spring:
  datasource:
    username: team_d
    password: green502
    jdbc-url: jdbc:mariadb://192.168.0.144:3306/team_d
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  type-aliases-package: com.team.winey
  mapper-locations: mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: /home/download

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: root
    url: jdbc:mariadb://localhost:3306/test
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:init/schema.sql
#      data-locations: classpath:init/data.sql

---

spring:
  config:
    activate:
      on-profile: "prod"
  data:
    redis:
      host: 192.168.0.144
  datasource:
    url: jdbc:mariadb://192.168.0.144:3306/team_d
file:
  dir: /home/download